---
deployment:
  tasks:
    - export REPOPATH=/home/smertnik/repositories/smertnik/*
    - export SITEPATH=/home/smertnik/me.smertnik.site/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH
